"""Build dist/in-vivo.css and dist/in-vivo.js.

Sources: src/style.css, src/markup.html, src/app.template.js, the reusable prototype code
sections in tools/parts.json, and the morph shapes + eye path inlined in reference/prototype.html.
Usage: python3 tools/build.py <version>
"""
import json, re, sys, pathlib
R = pathlib.Path(__file__).resolve().parent.parent
version = sys.argv[1] if len(sys.argv) > 1 else '0.0.0'

def must(s, a, b, n=1):
    assert s.count(a) == n, (a[:70], s.count(a))
    return s.replace(a, b)

# ---- css: everything nested under #iv-root so nothing leaks into or out of Cargo
css = (R / 'src/style.css').read_text()
kf = '@keyframes iv-fade{from{opacity:0}to{opacity:1}}\n'
out_css = (f'/* in vivo, Cargo layer v{version}. Generated by tools/build.py. */\n'
                      '/* Cargo renders its pages but we show our own views; its cart and checkout overlay stays visible */\n'
           'html.iv-on body > .content{display:none!important}\n'
           'html.iv-on, html.iv-on body{background:#fff}\n'
           '/* the app waits for this before it measures anything */\n'
           'html{--iv-css:1}\n'
           + kf + '#iv-root{\n' + css + '\n}\n')
(R / 'dist/app.css').write_text(out_css)

# ---- js
parts = json.loads((R / 'tools/parts.json').read_text())
parts['helpers'] = must(parts['helpers'], "const $ = (s, r = document) => r.querySelector(s);", "const $ = (s, r = root) => r.querySelector(s);")
pn = parts['panel']
pn = must(pn, 'href="#${i.page}"', 'href="/${esc(i.page)}"')
pn = must(pn, '<a class="row about" href="#about"><span>about</span><span class="reg"></span><span class="meta" aria-hidden="true">→</span></a>',
          '${ABOUT ? `<a class="row about" href="/${esc(ABOUT)}"><span>about</span><span class="reg"></span><span class="meta" aria-hidden="true">→</span></a>` : \'\'}')
pn = must(pn, '<span class="meta">${i.cat}</span>', '<span class="meta">${esc(i.cat)}</span>')
parts['panel'] = pn
parts['flight'] = must(parts['flight'], 'document.body.appendChild(fly);', 'root.appendChild(fly);')
parts['split'] = must(parts['split'], "getComputedStyle(document.documentElement).getPropertyValue('--g')", "getComputedStyle(root).getPropertyValue('--g')")

proto = (R / 'reference/prototype.html').read_text()
shapes = re.search(r'^const IV_SHAPES = .*$', proto, re.M).group(0)
eye = re.search(r"^const EYE_D = '([^']*)';$", proto, re.M).group(1)
markup = (R / 'src/markup.html').read_text()
markup = must(markup, 'href="#index" id="home"', 'href="/" id="home"')
# drop the prototype's outer <div class="iv"> wrapper around header/main/footer? keep it: it carries the page padding

js = (R / 'src/app.template.js').read_text()
for k, v in parts.items():
    js = must(js, '{{%s}}' % k, v)
js = js.replace('%%VERSION%%', version)
js = must(js, '%%SHAPES%%', shapes)
js = must(js, '%%EYE%%', eye)
js = must(js, '%%MARKUP%%', json.dumps(markup))
assert '{{' not in js and '%%' not in js
(R / 'dist/app.js').write_text(js)
(R / 'dist/in-vivo.js').write_text((R / 'src/bootstrap.js').read_text())
(R / 'dist/in-vivo.css').write_text((R / 'src/bootstrap.css').read_text())
print('built', version, len(out_css), 'css bytes', len(js), 'js bytes')
